# Generated by Django 5.2.5 on 2025-08-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='original',
            new_name='original_image',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='processed',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='bw_image',
            field=models.ImageField(blank=True, null=True, upload_to='bw/'),
        ),
    ]
